environment = "dev"
aws_region = "eu-central-1"
repository_name = "softkit-nestjs-boilerplate"
project_name = "platform"
org_name = "softkitit"
tf_state_file_name = "dev-platform-terraform.tfstate"
dynamo_db_table_name = "dev-softkitit-platform"
s3_bucket_name = "dev-softkitit-platform"
